// A Scintilla lexer backed by tree-sitter, for Elixir and HEEx.
//
// Why a parser rather than a state machine: HEEx is a three-level embedding --
// Elixir -> ~H"""...""" -> HTML -> {...} / <%= %> -> Elixir -- and the `{` that
// opens an expression is only an expression opener depending on the surrounding
// HTML tag state. Regex/state-machine lexers get this wrong in ways their
// authors have not been able to fix; VS Code's HEEx grammar has been visibly
// broken on `mix format` output since 2021. A parser makes the nesting fall out
// for free.
//
// Grammars and queries live in the submodules (deps/tree-sitter-*), Apache-2.0
// (Elixir) and MIT (HEEx and the tree-sitter runtime). See THIRD-PARTY-NOTICES.
//
// Structure: parse the document with the root grammar, run its highlight query,
// then run its injection query to find embedded regions and recurse into them
// with ts_parser_set_included_ranges. Every capture from every layer is
// collected as a (range, depth, pattern) triple, then sorted and painted over a
// flat style buffer -- the sort is what implements tree-sitter's precedence
// rules, and getting it right is most of the subtlety here.

#include <cstdlib>
#include <cassert>
#include <cstring>
#include <cstdint>
#include <cstdio>
#include <cstdarg>
#include <chrono>

#include <string>
#include <string_view>
#include <vector>
#include <map>
#include <algorithm>
#include <functional>
#include <iterator>
#include <regex>

#include "ILexer.h"
#include "Scintilla.h"
#include "SciLexer.h"

#include "WordList.h"
#include "LexAccessor.h"
#include "Accessor.h"
#include "StyleContext.h"
#include "CharacterSet.h"
#include "LexerModule.h"
#include "OptionSet.h"
#include "DefaultLexer.h"

#include <tree_sitter/api.h>

#include <turbo/lexts.h>

using namespace Scintilla;
using namespace Lexilla;

extern "C" {
const TSLanguage *tree_sitter_elixir(void);
const TSLanguage *tree_sitter_heex(void);
const TSLanguage *tree_sitter_html(void);
const TSLanguage *tree_sitter_css(void);
const TSLanguage *tree_sitter_javascript(void);
}

namespace turbo {
// Generated by CMake from the grammars' own query files; see TSQueries.cxx.in.
extern const char kQueryElixirHighlights[];
extern const char kQueryElixirInjections[];
extern const char kQueryHeexHighlights[];
extern const char kQueryHeexInjections[];
extern const char kQueryHtmlHighlights[];
extern const char kQueryHtmlInjections[];
extern const char kQueryCssHighlights[];
extern const char kQueryJsHighlights[];
extern const char kQueryJsHighlightsJsx[];
extern const char kQueryJsInjections[];
} // namespace turbo

namespace {

using namespace turbo;

constexpr int kNoStyle = -1;     // capture that must paint nothing
constexpr int kMaxDepth = 5;     // elixir -> heex -> elixir -> ... guard

// Set TURBO_TS_LOG=/path to record what each Lex() actually did. Injections fan
// out (one child parse per embedded expression), so "how many layers did that
// buffer cost" is the number worth being able to see.
struct LexStats { int layers = 0; int parses = 0; };

void tsLog(const char *fmt, ...)
{
    static FILE *f = [] () -> FILE * {
        const char *path = getenv("TURBO_TS_LOG");
        return (path && path[0]) ? fopen(path, "w") : nullptr;
    }();
    if (!f)
        return;
    va_list ap;
    va_start(ap, fmt);
    vfprintf(f, fmt, ap);
    va_end(ap);
    fflush(f);
}

struct CaptureMap { const char *name; int style; };

// The grammars' capture names, mapped per grammar. This is not merely
// convenient: "attribute" is a module attribute (@moduledoc) in Elixir but an
// HTML attribute name in HEEx, and they must not share a colour.
constexpr CaptureMap kElixirCaptures[] = {
    {"punctuation",               SCE_TS_PUNCTUATION},
    {"punctuation.bracket",       SCE_TS_PUNCTUATION},
    {"punctuation.delimiter",     SCE_TS_PUNCTUATION},
    {"punctuation.special",       SCE_TS_EMBEDDED},      // the #{ } of interpolation
    {"comment",                   SCE_TS_COMMENT},
    {"comment.unused",            SCE_TS_COMMENT},
    {"comment.doc",               SCE_TS_COMMENT_DOC},
    // The whole of `@moduledoc "..."` is documentation, and the query captures
    // the `@` as part of it -- so styling the name as an attribute would leave a
    // stray comment-coloured `@` in front of a preprocessor-coloured word. Colour
    // it all as a doc comment. Ordinary attributes (@spec, @impl) are captured as
    // plain "attribute" and keep the preprocessor colour.
    {"comment.doc.__attribute__", SCE_TS_COMMENT_DOC},
    {"constant",                  SCE_TS_CONSTANT},
    {"constant.builtin",          SCE_TS_CONSTANT},
    {"number",                    SCE_TS_NUMBER},
    {"variable",                  SCE_TS_VARIABLE},
    {"embedded",                  SCE_TS_EMBEDDED},
    {"string",                    SCE_TS_STRING},
    {"string.escape",             SCE_TS_STRING_ESCAPE},
    {"string.special",            SCE_TS_STRING_SPECIAL},
    {"string.special.symbol",     SCE_TS_SYMBOL},
    {"string.regex",              SCE_TS_REGEX},
    {"function",                  SCE_TS_FUNCTION},
    {"property",                  SCE_TS_PROPERTY},
    {"keyword",                   SCE_TS_KEYWORD},
    {"operator",                  SCE_TS_OPERATOR},
    {"attribute",                 SCE_TS_ATTRIBUTE},
    {"module",                    SCE_TS_MODULE},
    // "__name__" is deliberately absent. It is an internal helper the Elixir
    // query uses to test a sigil's name with #any-of?; painting it would
    // overwrite the sigil body's own style.
};

constexpr CaptureMap kHeexCaptures[] = {
    {"punctuation.bracket",   SCE_TS_PUNCTUATION},
    {"punctuation.delimiter", SCE_TS_PUNCTUATION},
    {"keyword",               SCE_TS_KEYWORD},
    {"comment",               SCE_TS_COMMENT},
    {"operator",              SCE_TS_OPERATOR},
    {"string",                SCE_TS_STRING},
    {"string.special",        SCE_TS_STRING_SPECIAL},
    {"constant",              SCE_TS_CONSTANT},
    {"tag",                   SCE_TS_TAG},
    {"module",                SCE_TS_MODULE},
    {"function",              SCE_TS_FUNCTION},
    {"attribute",             SCE_TS_TAG_ATTR},          // HTML attribute, not @moduledoc
    // "error" is deliberately absent. tree-sitter produces ERROR nodes on almost
    // every keystroke as you type an incomplete expression; painting them would
    // make the buffer strobe.
};

constexpr CaptureMap kHtmlCaptures[] = {
    {"tag",                 SCE_TS_TAG},
    {"attribute",           SCE_TS_TAG_ATTR},
    {"string",              SCE_TS_STRING},
    {"comment",             SCE_TS_COMMENT},
    {"constant",            SCE_TS_CONSTANT},        // doctype
    {"punctuation.bracket", SCE_TS_PUNCTUATION},
    // "tag.error" omitted: same strobing argument as HEEx's "error".
};

constexpr CaptureMap kCssCaptures[] = {
    {"property",              SCE_TS_TAG_ATTR},      // colour, display, --gap
    {"attribute",             SCE_TS_TAG_ATTR},
    {"tag",                   SCE_TS_TAG},           // element selectors
    {"type",                  SCE_TS_MODULE},
    {"keyword",               SCE_TS_KEYWORD},
    {"media",                 SCE_TS_KEYWORD},
    {"supports",              SCE_TS_KEYWORD},
    {"charset",               SCE_TS_KEYWORD},
    {"import",                SCE_TS_KEYWORD},
    {"namespace",             SCE_TS_KEYWORD},
    {"keyframes",             SCE_TS_KEYWORD},
    {"function",              SCE_TS_FUNCTION},      // rgb(), var()
    {"variable",              SCE_TS_CONSTANT},      // --custom-property
    {"string",                SCE_TS_STRING},
    {"string.special",        SCE_TS_STRING_SPECIAL},
    {"number",                SCE_TS_NUMBER},
    {"operator",              SCE_TS_OPERATOR},
    {"punctuation.bracket",   SCE_TS_PUNCTUATION},
    {"punctuation.delimiter", SCE_TS_PUNCTUATION},
    {"comment",               SCE_TS_COMMENT},
};

constexpr CaptureMap kJsCaptures[] = {
    {"keyword",               SCE_TS_KEYWORD},
    {"string",                SCE_TS_STRING},
    {"string.special",        SCE_TS_REGEX},         // regex literals
    {"number",                SCE_TS_NUMBER},
    {"comment",               SCE_TS_COMMENT},
    {"operator",              SCE_TS_OPERATOR},
    {"punctuation.bracket",   SCE_TS_PUNCTUATION},
    {"punctuation.delimiter", SCE_TS_PUNCTUATION},
    {"punctuation.special",   SCE_TS_EMBEDDED},      // the ${ } of a template literal
    {"embedded",              SCE_TS_EMBEDDED},
    {"function",              SCE_TS_FUNCTION},
    {"function.builtin",      SCE_TS_FUNCTION},
    {"function.method",       SCE_TS_FUNCTION},
    {"constructor",           SCE_TS_MODULE},        // class names
    {"constant",              SCE_TS_CONSTANT},
    {"constant.builtin",      SCE_TS_CONSTANT},
    {"variable",              SCE_TS_VARIABLE},
    {"variable.builtin",      SCE_TS_CONSTANT},      // this, super
    {"property",              SCE_TS_PROPERTY},
    {"tag",                   SCE_TS_TAG},           // JSX
    {"attribute",             SCE_TS_TAG_ATTR},      // JSX
};

// ---------------------------------------------------------------------------
// Query predicates.
//
// The C API stores predicates but does not evaluate them -- that lives in the
// Rust binding. We must evaluate the ones these grammars actually use:
// #eq?, #match?, #any-of? (and #set!, which carries the injection directives).

struct PredArg {
    bool isCapture = false;
    uint32_t capture = 0;
    std::string str;
};

struct Predicate {
    std::string op;
    std::vector<PredArg> args;
    std::regex re;
    bool hasRe = false;
};

// `(#offset! @cap sr sc er ec)` shifts the captured range's start and end points
// by the given row/column deltas. HEEx uses it to peel a <script>...</script>
// tag down to its contents (it captures the whole tag, then trims 1 row off the
// front and 9 columns off the back). Ignoring it -- as tree-sitter-highlight
// does -- means handing the JavaScript parser the surrounding markup, which is a
// syntax error, so the script block simply does not highlight.
struct InjOffset {
    int startRow = 0, startCol = 0, endRow = 0, endCol = 0;
    bool set = false;
};

struct InjSettings {
    std::string language;
    bool combined = false;
    bool includeChildren = false;
    InjOffset offset;
};

std::string queryStr(const TSQuery *q, uint32_t id)
{
    uint32_t len = 0;
    const char *s = ts_query_string_value_for_id(q, id, &len);
    return std::string(s, len);
}

std::string captureName(const TSQuery *q, uint32_t id)
{
    uint32_t len = 0;
    const char *s = ts_query_capture_name_for_id(q, id, &len);
    return std::string(s, len);
}

// Predicate steps are a flat array terminated by Done sentinels -- one Done per
// predicate. They must be split on that sentinel, NOT read in fixed groups of
// three: #any-of? is variadic and "#set! injection.combined" is only two steps.
std::vector<std::vector<Predicate>> loadPredicates(const TSQuery *q)
{
    std::vector<std::vector<Predicate>> byPattern(ts_query_pattern_count(q));
    for (uint32_t p = 0; p < byPattern.size(); ++p) {
        uint32_t n = 0;
        const TSQueryPredicateStep *steps = ts_query_predicates_for_pattern(q, p, &n);
        Predicate cur;
        bool first = true;
        for (uint32_t i = 0; i < n; ++i) {
            const TSQueryPredicateStep &s = steps[i];
            if (s.type == TSQueryPredicateStepTypeDone) {
                if (!cur.op.empty()) {
                    if ((cur.op == "match?" || cur.op == "not-match?") &&
                        cur.args.size() >= 2 && !cur.args[1].isCapture) {
                        try {
                            // ECMAScript is fine for every regex these grammars
                            // actually use (^_, ^[sS]$, ^[rR]$, ^on[a-z]+$), and
                            // compiling here keeps std::regex off the hot path.
                            cur.re.assign(cur.args[1].str, std::regex::ECMAScript);
                            cur.hasRe = true;
                        } catch (const std::regex_error &) {
                            cur.hasRe = false;
                        }
                    }
                    byPattern[p].push_back(std::move(cur));
                }
                cur = Predicate();
                first = true;
                continue;
            }
            if (first) {
                cur.op = queryStr(q, s.value_id);   // the operator is always a string
                first = false;
                continue;
            }
            PredArg a;
            if (s.type == TSQueryPredicateStepTypeCapture) {
                a.isCapture = true;
                a.capture = s.value_id;
            } else {
                a.str = queryStr(q, s.value_id);
            }
            cur.args.push_back(std::move(a));
        }
    }
    return byPattern;
}

// #set! directives are returned in the same step array as the real predicates,
// so the injection settings are read straight out of them.
std::vector<InjSettings> loadInjSettings(const std::vector<std::vector<Predicate>> &preds)
{
    std::vector<InjSettings> out(preds.size());
    for (size_t p = 0; p < preds.size(); ++p)
        for (const Predicate &pr : preds[p]) {
            if (pr.op != "set!" || pr.args.empty() || pr.args[0].isCapture)
                continue;
            const std::string &key = pr.args[0].str;
            if (key == "injection.language" && pr.args.size() >= 2)
                out[p].language = pr.args[1].str;
            else if (key == "injection.combined")
                out[p].combined = true;
            else if (key == "injection.include-children")
                out[p].includeChildren = true;
        }
    // #offset! is a predicate, not a #set!, so it arrives with the capture as its
    // first argument and the four deltas after it.
    for (size_t p = 0; p < preds.size(); ++p)
        for (const Predicate &pr : preds[p]) {
            if (pr.op != "offset!" || pr.args.size() < 5)
                continue;
            out[p].offset.startRow = atoi(pr.args[1].str.c_str());
            out[p].offset.startCol = atoi(pr.args[2].str.c_str());
            out[p].offset.endRow = atoi(pr.args[3].str.c_str());
            out[p].offset.endCol = atoi(pr.args[4].str.c_str());
            out[p].offset.set = true;
        }
    return out;
}

struct Grammar {
    const TSLanguage *language = nullptr;
    TSQuery *highlights = nullptr;
    TSQuery *injections = nullptr;
    std::vector<int> captureStyle;                  // highlight capture id -> style
    std::vector<uint32_t> injContentCaptures;       // injection capture ids named injection.content
    std::vector<uint32_t> injLangCaptures;          // ... named injection.language (dynamic form)
    std::vector<std::vector<Predicate>> hlPreds;
    std::vector<std::vector<Predicate>> injPreds;
    std::vector<InjSettings> injSettings;
    bool ok = false;
};

int styleForCapture(const std::string &name, const CaptureMap *map, size_t n)
{
    // Dotted-prefix fallback: string.special.symbol -> string.special -> string.
    std::string probe = name;
    for (;;) {
        for (size_t i = 0; i < n; ++i)
            if (probe == map[i].name)
                return map[i].style;
        auto dot = probe.rfind('.');
        if (dot == std::string::npos)
            return kNoStyle;
        probe.resize(dot);
    }
}

TSQuery *compileQuery(const TSLanguage *lang, const std::string &src)
{
    uint32_t errOffset = 0;
    TSQueryError errType = TSQueryErrorNone;
    return ts_query_new(lang, src.c_str(), (uint32_t) src.size(), &errOffset, &errType);
}

// Queries come in pieces and must be concatenated, for three separate reasons:
//   - a grammar can split them (JavaScript keeps JSX in highlights-jsx.scm, PHP
//     keeps its HTML injection in injections-text.scm);
//   - a dialect can be a delta on another (TypeScript's highlights are only the
//     type-syntax additions to JavaScript's);
//   - a query can open with `; inherits: html`, which is an nvim-treesitter
//     convention rather than anything tree-sitter core understands. Prepending
//     the inherited grammar's source here *is* the implementation of it.
std::string concatQueries(std::initializer_list<const char *> srcs)
{
    std::string out;
    for (const char *s : srcs)
        if (s && *s) {
            out += s;
            out += '\n';
        }
    return out;
}

Grammar buildGrammar(const TSLanguage *lang,
                     std::initializer_list<const char *> hlSrcs,
                     std::initializer_list<const char *> injSrcs,
                     const CaptureMap *map, size_t nMap)
{
    Grammar g;
    g.language = lang;
    g.highlights = compileQuery(lang, concatQueries(hlSrcs));
    g.injections = compileQuery(lang, concatQueries(injSrcs));
    if (!g.highlights || !g.injections)
        return g;

    const uint32_t nHl = ts_query_capture_count(g.highlights);
    g.captureStyle.resize(nHl, kNoStyle);
    for (uint32_t i = 0; i < nHl; ++i)
        g.captureStyle[i] = styleForCapture(captureName(g.highlights, i), map, nMap);

    const uint32_t nInj = ts_query_capture_count(g.injections);
    for (uint32_t i = 0; i < nInj; ++i) {
        const std::string n = captureName(g.injections, i);
        if (n == "injection.content")
            g.injContentCaptures.push_back(i);
        else if (n == "injection.language")
            g.injLangCaptures.push_back(i);
    }

    g.hlPreds = loadPredicates(g.highlights);
    g.injPreds = loadPredicates(g.injections);
    g.injSettings = loadInjSettings(g.injPreds);
    g.ok = true;
    return g;
}

// The grammars and their compiled queries are immutable and shared by every
// editor; build them once, on first use.
const Grammar &elixirGrammar()
{
    static const Grammar g = buildGrammar(tree_sitter_elixir(),
                                          {kQueryElixirHighlights},
                                          {kQueryElixirInjections},
                                          kElixirCaptures, std::size(kElixirCaptures));
    return g;
}

const Grammar &heexGrammar()
{
    static const Grammar g = buildGrammar(tree_sitter_heex(),
                                          {kQueryHeexHighlights},
                                          {kQueryHeexInjections},
                                          kHeexCaptures, std::size(kHeexCaptures));
    return g;
}

const Grammar &htmlGrammar()
{
    static const Grammar g = buildGrammar(tree_sitter_html(),
                                          {kQueryHtmlHighlights},
                                          {kQueryHtmlInjections},
                                          kHtmlCaptures, std::size(kHtmlCaptures));
    return g;
}

const Grammar &cssGrammar()
{
    static const Grammar g = buildGrammar(tree_sitter_css(),
                                          {kQueryCssHighlights},
                                          {""},                 // css injects nothing
                                          kCssCaptures, std::size(kCssCaptures));
    return g;
}

const Grammar &jsGrammar()
{
    static const Grammar g = buildGrammar(tree_sitter_javascript(),
                                          {kQueryJsHighlights, kQueryJsHighlightsJsx},
                                          {kQueryJsInjections},
                                          kJsCaptures, std::size(kJsCaptures));
    return g;
}

struct NamedGrammar { const char *name; const Grammar &(*get)(); };

constexpr NamedGrammar kGrammars[] = {
    {"elixir",     elixirGrammar},
    {"heex",       heexGrammar},
    {"html",       htmlGrammar},
    {"css",        cssGrammar},
    {"javascript", jsGrammar},
    {"js",         jsGrammar},      // alias: some queries spell it this way
};

// An injection naming a language we have not vendored is skipped, and the region
// simply keeps its host's styling. That is deliberate and load-bearing: the
// grammars' own queries ask for regex, sql, markdown, python, jsdoc, vue and
// more, and we are never going to carry all of them.
const Grammar *grammarNamed(const std::string &name)
{
    for (const NamedGrammar &n : kGrammars)
        if (name == n.name) {
            const Grammar &g = n.get();
            return g.ok ? &g : nullptr;
        }
    return nullptr;
}

std::string_view nodeText(const std::string &text, TSNode n)
{
    const uint32_t s = ts_node_start_byte(n);
    const uint32_t e = ts_node_end_byte(n);
    if (s >= e || e > text.size())
        return {};
    return std::string_view(text).substr(s, e - s);
}

bool predicatesPass(const std::vector<Predicate> &preds, const TSQueryMatch &m,
                    const std::string &text)
{
    auto capturedText = [&](uint32_t captureId) -> std::string_view {
        for (uint16_t i = 0; i < m.capture_count; ++i)
            if (m.captures[i].index == captureId)
                return nodeText(text, m.captures[i].node);
        return {};
    };

    for (const Predicate &p : preds) {
        if (p.op == "set!" || p.args.empty() || !p.args[0].isCapture)
            continue;                                  // directives and unknowns pass
        const std::string_view lhs = capturedText(p.args[0].capture);

        if (p.op == "eq?" || p.op == "not-eq?") {
            if (p.args.size() < 2) continue;
            const std::string_view rhs = p.args[1].isCapture
                ? capturedText(p.args[1].capture)
                : std::string_view(p.args[1].str);
            const bool eq = (lhs == rhs);
            if (eq != (p.op == "eq?"))
                return false;
        } else if (p.op == "match?" || p.op == "not-match?") {
            if (!p.hasRe) continue;
            // regex_search, not regex_match: the Elixir query uses "^_" to catch
            // an unused variable, and regex_match anchors both ends, so it would
            // only fire on a variable literally named "_".
            const std::string s(lhs);
            const bool hit = std::regex_search(s, p.re);
            if (hit != (p.op == "match?"))
                return false;
        } else if (p.op == "any-of?" || p.op == "not-any-of?") {
            bool hit = false;
            for (size_t i = 1; i < p.args.size(); ++i)
                if (!p.args[i].isCapture && lhs == p.args[i].str) {
                    hit = true;
                    break;
                }
            if (hit != (p.op == "any-of?"))
                return false;
        }
        // Anything else (#is?, #offset!, ...) is treated as passing, which is
        // what tree-sitter-highlight does with its general_predicates.
    }
    return true;
}

// One highlight from any layer. The fields beyond the range exist purely to make
// the precedence sort below expressible.
struct Hl {
    uint32_t start;
    uint32_t end;
    uint16_t pattern;
    uint8_t depth;
    char style;
};

struct PendingInjection {
    const Grammar *grammar;
    std::vector<TSRange> ranges;
};

TSRange rangeOf(TSNode n)
{
    TSRange r;
    r.start_byte = ts_node_start_byte(n);
    r.end_byte = ts_node_end_byte(n);
    r.start_point = ts_node_start_point(n);
    r.end_point = ts_node_end_point(n);
    return r;
}

std::vector<uint32_t> lineStartsOf(const std::string &text)
{
    std::vector<uint32_t> ls{0};
    for (uint32_t i = 0; i < text.size(); ++i)
        if (text[i] == '\n')
            ls.push_back(i + 1);
    return ls;
}

// A row/column pair, offset by #offset!'s deltas, converted to a byte. The
// deltas are signed and routinely push a column negative (HEEx trims -9 columns
// off the end of a </script>), so this works in signed arithmetic and clamps.
uint32_t byteAtOffset(const std::vector<uint32_t> &ls, size_t len, long row, long col)
{
    if (row < 0)
        return 0;
    if ((size_t) row >= ls.size())
        return (uint32_t) len;
    const long b = (long) ls[(size_t) row] + col;
    if (b < 0)
        return 0;
    if ((size_t) b > len)
        return (uint32_t) len;
    return (uint32_t) b;
}

// Derive the point from the byte rather than offsetting it separately, so the
// two halves of the TSRange cannot disagree.
TSPoint pointForByte(const std::vector<uint32_t> &ls, uint32_t b)
{
    auto it = std::upper_bound(ls.begin(), ls.end(), b);
    const size_t row = (size_t) (it - ls.begin()) - 1;
    TSPoint p;
    p.row = (uint32_t) row;
    p.column = b - ls[row];
    return p;
}

TSRange offsetRangeOf(TSNode n, const InjOffset &o, const std::vector<uint32_t> &ls, size_t len)
{
    const TSPoint sp = ts_node_start_point(n);
    const TSPoint ep = ts_node_end_point(n);
    TSRange r;
    r.start_byte = byteAtOffset(ls, len, (long) sp.row + o.startRow,
                                (long) sp.column + o.startCol);
    r.end_byte = byteAtOffset(ls, len, (long) ep.row + o.endRow,
                              (long) ep.column + o.endCol);
    if (r.end_byte < r.start_byte)
        r.end_byte = r.start_byte;
    r.start_point = pointForByte(ls, r.start_byte);
    r.end_point = pointForByte(ls, r.end_byte);
    return r;
}

// With injection.include-children off (the default), the injected ranges are the
// content node's extent minus each of its children -- so an interpolation inside
// the region is not fed to the child parser as if it were child-language source.
void appendRanges(std::vector<TSRange> &out, TSNode n, const InjSettings &st,
                  const std::vector<uint32_t> &ls, size_t len)
{
    if (st.offset.set) {
        // An offset trims the captured node down to the region that is actually
        // the other language, so children are irrelevant -- the trim is the point.
        out.push_back(offsetRangeOf(n, st.offset, ls, len));
        return;
    }
    if (st.includeChildren) {
        out.push_back(rangeOf(n));
        return;
    }
    uint32_t cursor = ts_node_start_byte(n);
    TSPoint cursorPt = ts_node_start_point(n);
    const uint32_t nChildren = ts_node_child_count(n);   // all children, not just named
    for (uint32_t i = 0; i < nChildren; ++i) {
        TSNode c = ts_node_child(n, i);
        const uint32_t cs = ts_node_start_byte(c);
        if (cs > cursor) {
            TSRange r;
            r.start_byte = cursor;
            r.end_byte = cs;
            r.start_point = cursorPt;
            r.end_point = ts_node_start_point(c);
            out.push_back(r);
        }
        cursor = ts_node_end_byte(c);
        cursorPt = ts_node_end_point(c);
    }
    const uint32_t e = ts_node_end_byte(n);
    if (cursor < e) {
        TSRange r;
        r.start_byte = cursor;
        r.end_byte = e;
        r.start_point = cursorPt;
        r.end_point = ts_node_end_point(n);
        out.push_back(r);
    }
}

// tree-sitter requires included ranges to be sorted and non-overlapping, and
// silently refuses the whole set otherwise.
void normalizeRanges(std::vector<TSRange> &r)
{
    r.erase(std::remove_if(r.begin(), r.end(),
                           [](const TSRange &x) { return x.end_byte <= x.start_byte; }),
            r.end());
    std::sort(r.begin(), r.end(),
              [](const TSRange &a, const TSRange &b) { return a.start_byte < b.start_byte; });
    std::vector<TSRange> out;
    for (TSRange &x : r)
        if (out.empty() || x.start_byte >= out.back().end_byte)
            out.push_back(x);
    r.swap(out);
}

// Parse one language layer, collect its highlights, then recurse into whatever
// it injects. Byte offsets are absolute throughout: included ranges make the
// child tree's nodes carry positions in the *original* document, which is what
// lets every layer's captures land in one flat style buffer.
void lexLayer(const Grammar &g, const std::string &text,
              const std::vector<uint32_t> &lineStarts,
              const std::vector<TSRange> &included, int depth,
              uint32_t startPos, uint32_t endPos, std::vector<Hl> &out, LexStats &stats)
{
    if (!g.ok || depth > kMaxDepth)
        return;
    stats.layers++;
    stats.parses++;

    TSParser *parser = ts_parser_new();
    if (!parser)
        return;
    if (!ts_parser_set_language(parser, g.language)) {
        ts_parser_delete(parser);
        return;
    }
    if (!included.empty() &&
        !ts_parser_set_included_ranges(parser, included.data(), (uint32_t) included.size())) {
        ts_parser_delete(parser);
        return;
    }
    TSTree *tree = ts_parser_parse_string(parser, nullptr, text.data(), (uint32_t) text.size());
    if (!tree) {
        ts_parser_delete(parser);
        return;
    }
    const TSNode root = ts_tree_root_node(tree);

    // --- highlights: limited to the range Scintilla asked us to style ---
    if (TSQueryCursor *cur = ts_query_cursor_new()) {
        ts_query_cursor_set_byte_range(cur, startPos, endPos);
        ts_query_cursor_exec(cur, g.highlights, root);
        TSQueryMatch m;
        while (ts_query_cursor_next_match(cur, &m)) {
            if (!predicatesPass(g.hlPreds[m.pattern_index], m, text))
                continue;
            for (uint16_t i = 0; i < m.capture_count; ++i) {
                const TSQueryCapture &c = m.captures[i];
                if (c.index >= g.captureStyle.size())
                    continue;
                const int style = g.captureStyle[c.index];
                if (style == kNoStyle)
                    continue;               // e.g. @__name__: paint nothing
                const uint32_t s = ts_node_start_byte(c.node);
                const uint32_t e = ts_node_end_byte(c.node);
                if (e <= s)
                    continue;
                out.push_back({s, e, m.pattern_index, (uint8_t) depth, (char) style});
            }
        }
        ts_query_cursor_delete(cur);
    }

    // --- injections: over the WHOLE tree, never byte-range limited ---
    //
    // A combined injection accumulates every match of its pattern across the
    // entire document into ONE child parse. HEEx needs this: `<%= if true do %>`
    // and `<% end %>` are two separate directive nodes, and parsed apart they are
    // both syntax errors -- fed as two included ranges to a single Elixir parse
    // they are one valid expression. Byte-range limiting this cursor would drop
    // whichever half is scrolled off-screen and break the pair.
    std::vector<PendingInjection> pending;
    // Keyed by (pattern, language), not by pattern alone. A combined injection
    // merges every match of its pattern into one child parse -- but JavaScript's
    // tagged-template pattern is both combined AND dynamically-languaged, so
    // keying on the pattern alone would feed a css`...` and an html`...` literal
    // to the same parser.
    std::map<std::pair<uint32_t, std::string>, std::vector<TSNode>> combined;

    if (TSQueryCursor *cur = ts_query_cursor_new()) {
        ts_query_cursor_exec(cur, g.injections, root);
        TSQueryMatch m;
        while (ts_query_cursor_next_match(cur, &m)) {
            if (!predicatesPass(g.injPreds[m.pattern_index], m, text))
                continue;
            const InjSettings &st = g.injSettings[m.pattern_index];

            // The language is usually fixed by `#set! injection.language`, but it
            // can also be dynamic: a capture named @injection.language carries the
            // name as its own text. That is how a tagged template literal picks its
            // language -- css`...` injects CSS, and styled.div`...` names a language
            // ("div") that resolves to nothing and is skipped, which is correct.
            std::string langName = st.language;
            if (langName.empty() && !g.injLangCaptures.empty())
                for (uint16_t i = 0; i < m.capture_count; ++i)
                    if (std::find(g.injLangCaptures.begin(), g.injLangCaptures.end(),
                                  m.captures[i].index) != g.injLangCaptures.end()) {
                        langName = std::string(nodeText(text, m.captures[i].node));
                        break;
                    }

            const Grammar *child = grammarNamed(langName);
            if (!child || !child->ok)
                continue;                   // not vendored: leave the region to its host
            for (uint16_t i = 0; i < m.capture_count; ++i) {
                const TSQueryCapture &c = m.captures[i];
                if (std::find(g.injContentCaptures.begin(), g.injContentCaptures.end(),
                              c.index) == g.injContentCaptures.end())
                    continue;
                if (st.combined) {
                    combined[{m.pattern_index, langName}].push_back(c.node);
                } else {
                    PendingInjection pi;
                    pi.grammar = child;
                    appendRanges(pi.ranges, c.node, st, lineStarts, text.size());
                    pending.push_back(std::move(pi));
                }
            }
        }
        ts_query_cursor_delete(cur);
    }

    for (auto &kv : combined) {
        const InjSettings &st = g.injSettings[kv.first.first];
        PendingInjection pi;
        pi.grammar = grammarNamed(kv.first.second);
        if (!pi.grammar)
            continue;
        for (TSNode n : kv.second)
            appendRanges(pi.ranges, n, st, lineStarts, text.size());
        pending.push_back(std::move(pi));
    }

    // Nodes belong to 'tree', so every range must be extracted before it dies.
    ts_tree_delete(tree);
    ts_parser_delete(parser);

    for (PendingInjection &pi : pending) {
        normalizeRanges(pi.ranges);
        if (pi.ranges.empty())
            continue;
        // Clear the host's styling under the injected region before the child
        // paints. An injected region is another language, not a string: Elixir
        // captures a ~H sigil's whole body as a sigil, so without this the plain
        // text of every template would inherit the sigil's string colour and the
        // buffer would read as one long literal. The ~H""" delimiters themselves
        // sit outside the content node, so they correctly stay string-coloured.
        for (const TSRange &r : pi.ranges)
            out.push_back({r.start_byte, r.end_byte, 0, (uint8_t) (depth + 1),
                           (char) SCE_TS_DEFAULT});
        lexLayer(*pi.grammar, text, lineStarts, pi.ranges, depth + 1, startPos, endPos,
                 out, stats);
    }
}

// ---------------------------------------------------------------------------

struct OptionsTS {
    bool fold = false;
    bool foldCompact = false;
};

struct OptionSetTS : public OptionSet<OptionsTS> {
    OptionSetTS() {
        DefineProperty("fold", &OptionsTS::fold);
        DefineProperty("fold.compact", &OptionsTS::foldCompact);
    }
};

LexicalClass lexicalClasses[] = {
    {SCE_TS_DEFAULT,        "SCE_TS_DEFAULT",        "default",        "White space"},
    {SCE_TS_COMMENT,        "SCE_TS_COMMENT",        "comment",        "Comment"},
    {SCE_TS_COMMENT_DOC,    "SCE_TS_COMMENT_DOC",    "comment documentation", "Doc comment"},
    {SCE_TS_KEYWORD,        "SCE_TS_KEYWORD",        "keyword",        "Keyword"},
    {SCE_TS_OPERATOR,       "SCE_TS_OPERATOR",       "operator",       "Operator"},
    {SCE_TS_PUNCTUATION,    "SCE_TS_PUNCTUATION",    "operator",       "Punctuation"},
    {SCE_TS_STRING,         "SCE_TS_STRING",         "literal string", "String"},
    {SCE_TS_STRING_ESCAPE,  "SCE_TS_STRING_ESCAPE",  "literal string", "Escape"},
    {SCE_TS_STRING_SPECIAL, "SCE_TS_STRING_SPECIAL", "literal string", "Sigil"},
    {SCE_TS_SYMBOL,         "SCE_TS_SYMBOL",         "literal",        "Atom"},
    {SCE_TS_REGEX,          "SCE_TS_REGEX",          "literal string", "Regex"},
    {SCE_TS_NUMBER,         "SCE_TS_NUMBER",         "literal numeric", "Number"},
    {SCE_TS_CONSTANT,       "SCE_TS_CONSTANT",       "literal",        "Constant"},
    {SCE_TS_VARIABLE,       "SCE_TS_VARIABLE",       "identifier",     "Variable"},
    {SCE_TS_FUNCTION,       "SCE_TS_FUNCTION",       "identifier",     "Function"},
    {SCE_TS_PROPERTY,       "SCE_TS_PROPERTY",       "identifier",     "Property"},
    {SCE_TS_MODULE,         "SCE_TS_MODULE",         "identifier",     "Module"},
    {SCE_TS_ATTRIBUTE,      "SCE_TS_ATTRIBUTE",      "preprocessor",   "Module attribute"},
    {SCE_TS_TAG,            "SCE_TS_TAG",            "identifier",     "Markup tag"},
    {SCE_TS_TAG_ATTR,       "SCE_TS_TAG_ATTR",       "identifier",     "Markup attribute"},
    {SCE_TS_EMBEDDED,       "SCE_TS_EMBEDDED",       "literal string interpolated", "Interpolation"},
    {SCE_TS_ERROR,          "SCE_TS_ERROR",          "error",          "Error"},
};

class LexerTS : public DefaultLexer {
    const Grammar &(*rootGrammar)();
    OptionsTS options;
    OptionSetTS osTS;

    // Cached between Lex and the Fold that immediately follows it, so folding
    // does not cost a second parse of the same text.
    std::string foldText;
    std::vector<int> foldLevels;

public:
    LexerTS(const char *name, int id, const Grammar &(*root)()) :
        DefaultLexer(name, id, lexicalClasses, std::size(lexicalClasses)),
        rootGrammar(root) {}

    void SCI_METHOD Release() override { delete this; }
    int SCI_METHOD Version() const override { return lvRelease5; }

    const char *SCI_METHOD PropertyNames() override { return osTS.PropertyNames(); }
    int SCI_METHOD PropertyType(const char *name) override { return osTS.PropertyType(name); }
    const char *SCI_METHOD DescribeProperty(const char *name) override {
        return osTS.DescribeProperty(name);
    }
    const char *SCI_METHOD PropertyGet(const char *key) override { return osTS.PropertyGet(key); }
    const char *SCI_METHOD DescribeWordListSets() override { return osTS.DescribeWordListSets(); }
    Sci_Position SCI_METHOD WordListSet(int, const char *) override { return -1; }

    Sci_Position SCI_METHOD PropertySet(const char *key, const char *val) override {
        return osTS.PropertySet(&options, key, val) ? 0 : -1;
    }

    void SCI_METHOD Lex(Sci_PositionU startPos, Sci_Position length, int initStyle,
                        IDocument *pAccess) override;
    void SCI_METHOD Fold(Sci_PositionU startPos, Sci_Position length, int initStyle,
                         IDocument *pAccess) override;

    void *SCI_METHOD PrivateCall(int, void *) override { return nullptr; }

    static ILexer5 *FactoryElixir() {
        return new LexerTS("elixir", SCLEX_TURBO_ELIXIR, elixirGrammar);
    }
    static ILexer5 *FactoryHeex() {
        return new LexerTS("heex", SCLEX_TURBO_HEEX, heexGrammar);
    }
};

void SCI_METHOD LexerTS::Lex(Sci_PositionU startPos, Sci_Position length, int,
                             IDocument *pAccess)
{
    // Lex is called across a C ABI boundary; an escaping exception would take
    // the process down rather than unwind.
    try {
        const Sci_Position docLen = pAccess->Length();
        if (docLen <= 0 || (Sci_Position) startPos >= docLen)
            return;

        std::string text((size_t) docLen, '\0');
        pAccess->GetCharRange(&text[0], 0, docLen);

        const uint32_t endPos =
            (uint32_t) std::min<Sci_Position>(docLen, (Sci_Position) startPos + length);

        std::vector<Hl> hls;
        LexStats stats;
        const std::vector<uint32_t> lineStarts = lineStartsOf(text);
        const auto t0 = std::chrono::steady_clock::now();
        lexLayer(rootGrammar(), text, lineStarts, {}, 0, (uint32_t) startPos, endPos,
                 hls, stats);
        const auto t1 = std::chrono::steady_clock::now();
        tsLog("lex %s bytes=%ld range=[%u,%u) layers=%d parses=%d hls=%zu %.1f ms\n",
              GetName(), (long) docLen, (unsigned) startPos, endPos,
              stats.layers, stats.parses, hls.size(),
              std::chrono::duration<double, std::milli>(t1 - t0).count());

        // Precedence, replicating tree-sitter-highlight:
        //   start ASC   -- paint left to right
        //   end   DESC  -- an OUTER node paints first, so the inner one overwrites
        //   depth ASC   -- an injected layer overwrites its host
        //   pattern ASC -- a LATER pattern in the .scm overwrites an earlier one,
        //                  which the Elixir query relies on to refine a @property
        //                  into a @function ("overrides above" in its comments)
        // Both existing tree-sitter/Scintilla projects get this wrong: tslexia is
        // first-wins, and NppTreeSitter omits the end DESC term, so a parent
        // sharing a start byte with its child can clobber the child.
        std::stable_sort(hls.begin(), hls.end(), [](const Hl &a, const Hl &b) {
            if (a.start != b.start) return a.start < b.start;
            if (a.end != b.end)     return a.end > b.end;
            if (a.depth != b.depth) return a.depth < b.depth;
            return a.pattern < b.pattern;
        });

        const size_t span = (size_t) (endPos - startPos);
        std::vector<char> styles(span, (char) SCE_TS_DEFAULT);
        for (const Hl &h : hls) {
            const uint32_t s = std::max<uint32_t>(h.start, startPos);
            const uint32_t e = std::min<uint32_t>(h.end, endPos);
            for (uint32_t p = s; p < e; ++p)
                styles[p - startPos] = h.style;
        }

        pAccess->StartStyling(startPos);
        pAccess->SetStyles((Sci_Position) span, styles.data());

        // Keep the text for Fold, which Scintilla calls straight after us.
        foldText.swap(text);
        foldLevels.clear();
    } catch (...) {
        return;
    }
}

void SCI_METHOD LexerTS::Fold(Sci_PositionU startPos, Sci_Position length, int,
                              IDocument *pAccess)
{
    if (!options.fold)
        return;
    try {
        const Sci_Position docLen = pAccess->Length();
        if (docLen <= 0)
            return;

        // Fold levels come from the tree: any named node spanning more than one
        // line is a fold region. That gives do/end blocks, maps, lists and HTML
        // tags without needing a hand-written folder -- and, unlike a keyword
        // counter, `do:` in a keyword list opens nothing because it is not a
        // do_block node.
        if (foldLevels.empty()) {
            std::string text((size_t) docLen, '\0');
            pAccess->GetCharRange(&text[0], 0, docLen);

            const Grammar &g = rootGrammar();
            if (!g.ok)
                return;
            TSParser *parser = ts_parser_new();
            if (!parser)
                return;
            if (!ts_parser_set_language(parser, g.language)) {
                ts_parser_delete(parser);
                return;
            }
            TSTree *tree = ts_parser_parse_string(parser, nullptr, text.data(),
                                                  (uint32_t) text.size());
            if (!tree) {
                ts_parser_delete(parser);
                return;
            }

            const Sci_Position nLines = pAccess->LineFromPosition(docLen) + 2;
            foldLevels.assign((size_t) nLines, 0);

            // Iterative walk: the AST depth is unbounded, and recursing it would
            // overflow the stack on a pathological file and take the editor with it.
            std::vector<TSNode> stack{ts_tree_root_node(tree)};
            while (!stack.empty()) {
                TSNode n = stack.back();
                stack.pop_back();
                const uint32_t sr = ts_node_start_point(n).row;
                const uint32_t er = ts_node_end_point(n).row;
                if (er > sr && ts_node_is_named(n))
                    for (uint32_t r = sr + 1; r <= er && r < foldLevels.size(); ++r)
                        foldLevels[r]++;
                const uint32_t nc = ts_node_child_count(n);
                for (uint32_t i = 0; i < nc; ++i)
                    stack.push_back(ts_node_child(n, i));
            }
            ts_tree_delete(tree);
            ts_parser_delete(parser);
        }

        const Sci_Position lineStart = pAccess->LineFromPosition(startPos);
        const Sci_Position lineEnd = pAccess->LineFromPosition(startPos + length);
        for (Sci_Position line = lineStart; line <= lineEnd; ++line) {
            if ((size_t) line >= foldLevels.size())
                break;
            const int here = SC_FOLDLEVELBASE + foldLevels[(size_t) line];
            const int next = ((size_t) line + 1 < foldLevels.size())
                ? SC_FOLDLEVELBASE + foldLevels[(size_t) line + 1]
                : here;
            int lev = here;
            if (next > here)
                lev |= SC_FOLDLEVELHEADERFLAG;
            pAccess->SetLevel((Sci_Position) line, lev);
        }
    } catch (...) {
        return;
    }
}

} // namespace

namespace Lexilla {
extern const LexerModule lmTurboTsElixir(SCLEX_TURBO_ELIXIR, LexerTS::FactoryElixir, "elixir");
extern const LexerModule lmTurboTsHeex(SCLEX_TURBO_HEEX, LexerTS::FactoryHeex, "heex");
}
